version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    command: [ "python3", "format_image/manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: .
    command: ['celery', '--workdir=format_image', '-A', 'format_image', 'worker' ]